### ISSUE TITLE
Shift from collecting feedback to collecting attendance

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#279]
@zachlatta Would you please explain the reasoning behind this?

**Comment by zachlatta** [comment]
Hiya, I'm so sorry for not getting back to this earlier. We've decided to shift our focus from collecting feedback to collecting attendance because we think feedback is better collected in calls or by talking to club members in-person. Attendance gives us a general high-level overview of the activity in a club.

Closing due to the resolution happening in person. I'll do my best to carry out more of these discussions on GitHub in the future.
