### ISSUE TITLE
Design Teespring shirts

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#365]

**Comment by MaxWofford** [comment]
![screenshot from 2015-12-08 22 37 45](https://cloud.githubusercontent.com/assets/5891442/11678407/7a4f7774-9dfc-11e5-8f2b-cfbfad2efeca.png)

@zachlatta

**Comment by MaxWofford** [comment]
Hmmmm. I think we could pull off red on the back

![screenshot from 2015-12-08 23 06 13](https://cloud.githubusercontent.com/assets/5891442/11678848/5b714680-9e00-11e5-87af-0f6938f81a21.png)

**Comment by jonleung** [comment]
I personally like

![image](https://cloud.githubusercontent.com/assets/654941/11732951/0f186a0c-9f5e-11e5-81cb-1c35ab341898.png)

over 

![image](https://cloud.githubusercontent.com/assets/654941/11732954/14b95f0c-9f5e-11e5-8d33-307a9d75b152.png)

and I like the white on black much more than the red on black for the back.

Only feedback that I have is that the logo on this shirt:

![image](https://cloud.githubusercontent.com/assets/654941/11732964/2f7599dc-9f5e-11e5-8122-5991b515b68d.png)


could be smaller by like 70% so that the logo doesn't take up the full width of the shirt.

Thoughts @MaxWofford?

**Comment by paked** [comment]
Also: orpheus shirt

**Comment by vaibhavyadaram** [comment]
Very first design is my favorite!

**Comment by JevinSidhu** [comment]
+1 to what @vaibhavyadaram and @jonleug said!

**Comment by zachlatta** [comment]
Agreed. First is my favorite as well. Would it be possible to add a slight
slant to it? Maybe not as much as the sticker, but I think a little slant
would be nice.

@MaxWofford, can you also post the Prophet Orpheus shirt you made? That was
awesome.

**Comment by MaxWofford** [comment]
It's live: https://teespring.com/stores/hack-club

I'll open a new issue for the prophet orpheus t-shirt
