### ISSUE TITLE
Obtain 32 Eventbrite signups (8 signups in each of the 4 cohorts)

### ISSUE THREAD

**Issue by paked** [hackclub/meta#407]
This equates to about 12 per workshop! If possible we should try get more.

**Comment by jonleung** [comment]
As discussed in our meeting tonight, Dec 16th 2015.

- We will drop 2 sessions, so we will have a total of 4 sessions
- We want a minimum of 8 signups per session

Therefore, we want a minimum of 32 signups or 21 additional signups (we have 11 currently).

**Comment by jonleung** [comment]
These are the tasks we are going to do in order to complete the above objective.

- [ ] Ask registered participants to bring a friend (@zachlatta)
- [ ] Ask Hack Camp participants to refer friends (@maxwofford)
- [ ] Ask Bay Area club leaders to refer friends (@paked)
  - Cookie prize for club with most referrals
- [ ] Ask friends who live in San Francisco who are in high school [[FB Search Query](https://www.facebook.com/search/19/users-younger/114952118516947/residents/present/me/friends/intersect)] (@jonleung, @MaxWofford)

**Comment by zachlatta** [comment]
All tasks have been done! Now we just need to hope those convert...

**Comment by paked** [comment]
![](https://45.media.tumblr.com/tumblr_lwirawN13q1r8o5tzo1_500.gif)

**Comment by paked** [comment]
![](![](https://45.media.tumblr.com/tumblr_lwirawN13q1r8o5tzo1_500.gif))

**Comment by zachlatta** [comment]
Only need 7 more signups!

**Comment by MaxWofford** [comment]
Closing this issue because Hack Series was AWESOME! (and is over)

![](http://quickme.me/success.gif)
