### ISSUE TITLE
Run Friday's Onboarding Call

### ISSUE THREAD

**Issue by kyleemile** [hackclub/meta#656]
Zach to record Tuesday's (9/6) 1pm PDT onboarding call, which I will use as reference. 
I will attend Tuesday's (9/6) 5pm PDT onboarding call. After reviewing the recorded onboarding
call and attending the 9/6 5pm PDT call, I'll be ready to run Friday's onboarding call on my own.

**Comment by zachlatta** [comment]
Closing this issue because it's not completely clear what needs to specifically be done for it to be closed.

Does this mean that you've ran an onboarding call by the end of the week? If so, I don't think that'll be possible because when we chatted earlier today, it sounded like you couldn't make any of the onboarding calls as a spectator while you're traveling.

**Comment by kyleemile** [comment]
We discussed that you'd record tomorrow morning's onboarding call and that
I'd attend the one in the evening. After reviewing the recorded onboarding
call and attending the one in the evening, I'd be ready to run Friday's
call on my own.

Can you help me understand how that's not clear?

**Comment by zachlatta** [comment]
That context wasn't included in the original issue, which is why it wasn't clear. If you included that in the issue's description, then this'd be fine. Feel free to reopen the issue and add that as the description.

Make it clear that the "deliverable" is you running Friday's onboarding call when you edit it.

**Comment by zachlatta** [comment]
Can you edit this issue's description to include what's described above? Closing in the meantime.
